export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';

export const START_LOADER = 'START_LOADER';
export const FINISH_LOADER = 'FINISH_LOADER';

export const FETCH_LOAD_MOVIES = 'FETCH_LOAD_MOVIES';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';

export const SELECTED_MENU = 'SELECTED_MENU';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';

export const FETCH_MOVIE_LOADING = 'FETCH_MOVIE_LOADING';
export const FETCH_MOVIE_FINISHED = 'FETCH_MOVIE_FINISHED';